### ISSUE TITLE
getDocumentByID - documentJson

### ISSUE THREAD

**Issue by lucibr** [HouseMormont/Backend#38]
@tudorlozba @iustiB @TirlaAlin 

La get DocumentById primesc documntJson sub forma unui string din care nu pot extrage datele pe care trebuie sa i le pun user0ului in form in asa fel incat sa le poata modifica.

Ar trebui ca pe raspuns sa se trimita din backend datele in forma in care au fost primite adica documentJson sa nu fie un string ci un array de json-uri.

**Comment by tudorlozba** [comment]
[http://stackoverflow.com/a/5726756](http://stackoverflow.com/a/5726756)

**Comment by lucibr** [comment]
@tudorlozba 
Tudor, eu zic sa lasi indicatiile cu stackoverflow deoparte. Era normal sa primesc datele din backend asa cum le-am trimis.

@TirlaAlin a rezolvat asta in doua randuri deci nu mai e o problema. Dar merci oricum de ajutor.
