### ISSUE TITLE
getDocumentByID nu imi returneaza campul 'cheltuieli' (array de json) pentru RN

### ISSUE THREAD

**Issue by lucibr** [HouseMormont/Backend#40]
@tudorlozba @iustiB 

Se salveaza in BD dar nu e returnat. La un call getDocumentByID pentru un document RN am un raspuns de genul: 

{"id_dispozitie":8,"versiune":0.1,"username":"luci","tip_initiator":1,"data":"22/01/2017","documentJson":{"dateFI":"bbb","sumaFSSolicitat":3,"dateCTA":"ccc","telSol":"074893432","dateFN":"aaa","denSponsor":"ddd","sumaSSolicitat":3,"venitProprSolicitat":3,"sumaFISolicitat":3,"dateFS":"eee","dateTA":"ggg","emailSol":"few@fe.com","numeG":"iiiii","emailG":"few@fe.com","bugetAprobat":0,"numeSol":"hhh","sumaFESolicitat":3,"buget":54,"sumaCTASolicitat":3,"sumaTASolicitat":33,"telG":"074893432","dateFE":"fff","sumaFNSolicitat":3}

**Comment by tudorlozba** [comment]
fixing  #commit:743c751dbbcd4c9809018fd30b4696d70cd5cd5b
