### ISSUE TITLE
Save RN nu functioneaza in backend

### ISSUE THREAD

**Issue by lucibr** [HouseMormont/Backend#41]
@tudorlozba @iustiB 
Am atasat printscreen cu stiva de erori

![error_savern](https://cloud.githubusercontent.com/assets/22635726/22181479/32f8a002-e096-11e6-8de1-c9c5ff78a13e.jpg)

**Comment by tudorlozba** [comment]
@lucibr pune versiunea documentului in request pe cheia "versionDoc" si se rezolva

**Comment by lucibr** [comment]
@tudorlozba 
asa e pusa acum

**Comment by tudorlozba** [comment]
![screen shot 2017-01-22 at 14 23 59](https://cloud.githubusercontent.com/assets/16645021/22182485/89ed6ff6-e0ae-11e6-9bb1-685503aa2771.png)
![screen shot 2017-01-22 at 14 19 52](https://cloud.githubusercontent.com/assets/16645021/22182484/89ecdbc2-e0ae-11e6-8f4f-eade49887a8d.png)

Nu le primesc... nu se pune versiunea
