### ISSUE TITLE
Calitate, autorizare si tip utilizator - String-uri  semnificative

### ISSUE THREAD

**Issue by lucibr** [HouseMormont/Backend#43]
Pentru calitate user, autoritate user si tip user, am nevoie de string-uri cu semnificatie sau mapare specificata pentru numerele primite
@tudorlozba

**Comment by tudorlozba** [comment]
![screen shot 2017-01-22 at 13 06 46](https://cloud.githubusercontent.com/assets/16645021/22182044/afaa1fce-e0a3-11e6-85b2-f76d351c31bb.png)
![screen shot 2017-01-22 at 13 06 37](https://cloud.githubusercontent.com/assets/16645021/22182043/afa6e214-e0a3-11e6-979e-9b14faa4d13b.png)
![screen shot 2017-01-22 at 13 06 30](https://cloud.githubusercontent.com/assets/16645021/22182042/afa63170-e0a3-11e6-9221-4769a7052715.png)

Call-urile returneaza ce trebuie @lucibr stringul este descrierea. In call pui id-ul
