### ISSUE TITLE
Problema la 'Finalizare'

### ISSUE THREAD

**Issue by lucibr** [HouseMormont/Backend#44]
Probabil problemele sunt din cauza ultimelor modificari.
![error_finalizare](https://cloud.githubusercontent.com/assets/22635726/22184037/2b35477a-e0d3-11e6-9cde-bfadc8869471.jpg)

@tudorlozba @iustiB @TirlaAlin

**Comment by tudorlozba** [comment]
Asta se intampla cand incerci sa finalizezi un draft care a fost finalizat deja. SQL-ul da eroare pentru ca exista deja un document cu id-ul 1 si cu versiunea 1 (spre exemplu)
