### ISSUE TITLE
Problema la save

### ISSUE THREAD

**Issue by lucibr** [HouseMormont/Backend#45]
Probabil tot din cauza ultimelor modificari
![error_savern](https://cloud.githubusercontent.com/assets/22635726/22184087/edbb1770-e0d3-11e6-862f-34745459d7bb.jpg)

@tudorlozba @iustiB @TirlaAlin

**Comment by tudorlozba** [comment]
Am testat si merge cum trebuie. Daca mai apare problema redeschidem issue.
