### ISSUE TITLE
Selectare multipla checkbox

### ISSUE THREAD

**Issue by tudorlozba** [HouseMormont/Backend#7]
Avem campuri cu checkbox-uri. Cum tratam cazurile. Se pot selecta mai multe sau doar unu singur. Spre exemplu la transport: auto, auto personal, tren, etc... Ce parere aveti @BCata  @lucibr ?

**Comment by lucibr** [comment]
Eu, cand am completat formular de delegatie la UTCN, am bifat doar o casuta, deci, pentru simplitate, putem sa acceptam un mijloc de transport unic.

**Comment by tudorlozba** [comment]
OK, asa facem. O sa va punem la review la commit-urile de db sa va uitati si voi ce si cum, poate aveti obiectii sau idei si ar fi bine sa facem asta inainte sa merge-uim
